import type { Metadata } from 'next';
import Footer from '@components/Footer/Footer';
import Header from '@components/Header/Header';
import ScrollToUpButton from '@components/ScrollToUpButton/ScrollToUpButton';

import { ModalProvider } from '../../context/ModalContext';

import { pridi } from './fonts';

import './globals.css';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" className={pridi.className}>
      <body>
        <ModalProvider>
          <Header />
          <main className={styles.main}>{children}</main>
          <Footer />
        </ModalProvider>
        <ScrollToUpButton />
      </body>
    </html>
  );
}
