import type { Metadata } from 'next';
import Footer from '@components/components/Footer/Footer';
import Header from '@components/components/Header/Header';
import ScrollToUpButton from '@components/components/ScrollToUpButton/ScrollToUpButton';

import { pridi } from './fonts';

import './globals.css';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" className={pridi.className}>
      {/* <head>
        <link rel="icon" href="/public/favicon.ico" sizes="any" />
      </head> */}
      <body>
        <Header />
        <main className={styles.main}>{children}</main>
        <Footer />
        <ScrollToUpButton />
      </body>
    </html>
  );
}
